# Generated by Django 5.1.3 on 2024-11-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
