# Generated by Django 5.1.3 on 2024-11-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
