# Generated by Django 5.1.3 on 2024-11-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
